### ISSUE TITLE
Remove qiskit-terra explicit dependency

### ISSUE THREAD

**Issue by 1ucian0** [vutuanhai237/qoop#1]
`qiskit-terra` is part of the `qiskit<1` meta-package. Keeping the double-dependency is redundant and forces to keep them in track. Additionally `qiskit-terra` is on its way to sunset.

Consider removing this dependency:

https://github.com/vutuanhai237/qoop/blob/3c94395c7e3c5008263661561b184cc23b96b38d/setup.py#L17

**Comment by vutuanhai237** [comment]
The commit c5c9cc4e255ea37984e45c18539b05e45c5c5eb1 has solved this problem.

**Comment by 1ucian0** [comment]
Awesome! Technically, this is a breaking change. Consider releasing 3.0 to keep users up to date too.
