### ISSUE TITLE
qiskit-ibmq-provider is not maintiained anymore

### ISSUE THREAD

**Issue by 1ucian0** [vutuanhai237/qoop#2]
Consider transition from `qiskit-ibmq-provider` to `qiskit-ibm-runtime` as the first one is not maintained since July 2023 https://github.com/Qiskit/qiskit-ibmq-provider

https://github.com/vutuanhai237/qoop/blob/3c94395c7e3c5008263661561b184cc23b96b38d/setup.py#L14

**Comment by vutuanhai237** [comment]
The commit c5c9cc4e255ea37984e45c18539b05e45c5c5eb1 has solved this problem.
